const selectors = Object.freeze({
  login: {
    root: 'login-screen',
    submitButton: 'login-submit-button',
  },
  landing: {
    root: 'landing-screen',
    createProjectButton: 'landing-create-project-button',
  },
  createProject: {
    root: 'create-project-screen',
    scrollView: 'create-project-scroll-view',
    nameInput: 'create-project-name-input',
    surveyDetailsInput: 'create-project-survey-details-input',
    instructionsInput: 'create-project-instructions-input',
    locationInput: 'create-project-location-input',
    dateInput: 'create-project-date-input',
    representingPartyDropdown: 'create-project-representing-party-dropdown',
    submitButton: 'create-project-submit-button',
  },
  createProjectMetadata: {
    root: 'create-project-metadata-screen',
    scrollView: 'create-project-metadata-scroll-view',
    containerIdInput: 'create-project-metadata-container-id-input',
    vesselNameInput: 'create-project-metadata-vessel-name-input',
    voyageNoInput: 'create-project-metadata-voyage-no-input',
    operatorInput: 'create-project-metadata-operator-input',
    portOfLoadingInput: 'create-project-metadata-port-of-loading-input',
    portOfDischargeInput: 'create-project-metadata-port-of-discharge-input',
    inspectionDateInput: 'create-project-metadata-inspection-date-input',
    inspectionTimeInput: 'create-project-metadata-inspection-time-input',
    submitButton: 'create-project-metadata-submit-button',
  },
  workspace: {
    root: 'project-workspace-screen',
    backButton: 'project-workspace-back-button',
    menuButton: 'project-workspace-menu-button',
    showMetadataMenuItem: 'overflow-menu-item-show-metadata',
    instructionsInput: 'project-workspace-instructions-input',
    saveInstructionsButton: 'project-workspace-save-instructions-button',
    showMetadataButton: 'project-workspace-show-metadata-button',
    uploadImagesButton: 'project-workspace-upload-images-button',
    firstImageThumbnail: 'project-workspace-image-thumbnail-0',
  },
  imageDetails: {
    root: 'image-details-screen',
    backButton: 'image-details-back-button',
    tagInput: 'image-details-tag-input',
    addTagButton: 'image-details-add-tag-button',
    saveButton: 'image-metadata-save-button',
  },
  editProjectMetadata: {
    root: 'edit-project-metadata-screen',
    backButton: 'edit-project-metadata-back-button',
    containerIdInput: 'edit-project-metadata-container-id-input',
    vesselNameInput: 'edit-project-metadata-vessel-name-input',
    voyageNoInput: 'edit-project-metadata-voyage-no-input',
    operatorInput: 'edit-project-metadata-operator-input',
    portOfLoadingInput: 'edit-project-metadata-port-of-loading-input',
    portOfDischargeInput: 'edit-project-metadata-port-of-discharge-input',
    inspectionDateInput: 'edit-project-metadata-inspection-date-input',
    inspectionTimeInput: 'edit-project-metadata-inspection-time-input',
    saveButton: 'edit-project-metadata-save-button',
  },
});

module.exports = { selectors };
